// Copyright 2026 RelyChan Pte. Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package authscheme defines types and interfaces for security schemes.
package authscheme

import (
	"bytes"
	"fmt"
	"net/http"

	"github.com/hasura/goenvconf"
	"github.com/relychan/goutils"
)

// HTTPClientAuthenticator abstracts an interface for injecting authentication value into HTTP requests.
type HTTPClientAuthenticator interface {
	// Authenticate the credential into the incoming request.
	Authenticate(req *http.Request, options ...AuthenticateOption) error
	// Close terminates internal processes before destroyed.
	Close() error
}

// HTTPClientAuthenticatorConfig abstracts an interface of the HTTP client authentication config.
type HTTPClientAuthenticatorConfig interface {
	goutils.IsZeroer
	// GetType gets the type of security scheme.
	GetType() HTTPClientAuthType
	// Validate checks if the instance is valid.
	Validate(strict bool) error
}

// HTTPClientAuthType represents the authentication scheme enum.
type HTTPClientAuthType uint8

const (
	HTTPAuthScheme HTTPClientAuthType = iota + 1
	BasicAuthScheme
	OAuth2Scheme
)

var enumValueHTTPClientAuthTypes = []string{
	"http",
	"basic",
	"oauth2",
}

// IsValid checks if the security scheme type is valid.
func (j HTTPClientAuthType) IsValid() bool {
	return j > 0 && j < 4
}

// String implements fmt.Stringer interface.
func (j HTTPClientAuthType) String() string {
	if !j.IsValid() {
		return ""
	}

	return enumValueHTTPClientAuthTypes[j-1]
}

// MarshalText encodes the receiver into UTF-8-encoded text and returns the result.
func (j HTTPClientAuthType) MarshalText() ([]byte, error) {
	return []byte(j.String()), nil
}

// UnmarshalText must be able to decode the form generated by MarshalText.
func (j *HTTPClientAuthType) UnmarshalText(text []byte) error {
	result, err := ParseHTTPClientAuthType(string(text))
	if err != nil {
		return err
	}

	*j = result

	return nil
}

// MarshalJSON marshals themselves into valid JSON.
func (j HTTPClientAuthType) MarshalJSON() ([]byte, error) {
	return goutils.QuoteBytes(j.String()), nil
}

// UnmarshalJSON unmarshals a JSON description of themselves.
func (j *HTTPClientAuthType) UnmarshalJSON(input []byte) error {
	value := bytes.Trim(input, `"`)

	return j.UnmarshalText(value)
}

// ParseHTTPClientAuthType parses SecurityScheme from string.
func ParseHTTPClientAuthType(value string) (HTTPClientAuthType, error) {
	switch value {
	case "basic":
		return BasicAuthScheme, nil
	case "http":
		return HTTPAuthScheme, nil
	case "oauth2":
		return OAuth2Scheme, nil
	default:
		return 0, fmt.Errorf(
			"%w; got: %s",
			errInvalidHTTPClientAuthType,
			value,
		)
	}
}

// GetSupportedHTTPClientAuthTypes get the list of supported security scheme types.
func GetSupportedHTTPClientAuthTypes() []string {
	return enumValueHTTPClientAuthTypes
}

// AuthLocation represents the location enum for setting authentication value.
type AuthLocation uint8

const (
	InHeader AuthLocation = iota
	InQuery
	InCookie
)

var enumValuesAuthLocations = []string{"header", "query", "cookie"}

// IsValid checks if the security scheme type is valid.
func (j AuthLocation) IsValid() bool {
	return j < 3
}

// String implements fmt.Stringer interface.
func (j AuthLocation) String() string {
	if !j.IsValid() {
		return ""
	}

	return enumValuesAuthLocations[j]
}

// MarshalText encodes the receiver into UTF-8-encoded text and returns the result.
func (j AuthLocation) MarshalText() ([]byte, error) {
	return []byte(j.String()), nil
}

// UnmarshalText must be able to decode the form generated by MarshalText.
func (j *AuthLocation) UnmarshalText(text []byte) error {
	result, err := ParseAuthLocation(string(text))
	if err != nil {
		return err
	}

	*j = result

	return nil
}

// MarshalJSON marshals themselves into valid JSON.
func (j AuthLocation) MarshalJSON() ([]byte, error) {
	return goutils.QuoteBytes(j.String()), nil
}

// UnmarshalJSON unmarshals a JSON description of themselves.
func (j *AuthLocation) UnmarshalJSON(input []byte) error {
	value := bytes.Trim(input, `"`)

	return j.UnmarshalText(value)
}

// ParseAuthLocation parses the auth location from string.
func ParseAuthLocation(value string) (AuthLocation, error) {
	switch value {
	case "header":
		return InHeader, nil
	case "query":
		return InQuery, nil
	case "cookie":
		return InCookie, nil
	default:
		return 255, fmt.Errorf(
			"%w; got: %s",
			errInvalidAuthLocation,
			value,
		)
	}
}

// GetSupportedAuthLocations get the list of supported auth locations.
func GetSupportedAuthLocations() []string {
	return enumValuesAuthLocations
}

// AuthenticateOptions represents custom options for the authentication.
type AuthenticateOptions struct {
	Name string
}

// AuthenticateOption adds custom options to the authenticate request.
type AuthenticateOption func(*AuthenticateOptions)

// WithAuthenticationName creates an option to set the authentication name.
func WithAuthenticationName(name string) AuthenticateOption {
	return func(ao *AuthenticateOptions) {
		ao.Name = name
	}
}

// HTTPClientAuthenticatorOptions define common options for the authenticator client.
type HTTPClientAuthenticatorOptions struct {
	GetEnv goenvconf.GetEnvFunc
}

// NewHTTPClientAuthenticatorOptions creates a new [HTTPClientAuthenticatorOptions] instance.
func NewHTTPClientAuthenticatorOptions(
	options ...HTTPClientAuthenticatorOption,
) *HTTPClientAuthenticatorOptions {
	result := &HTTPClientAuthenticatorOptions{}

	for _, opt := range options {
		opt(result)
	}

	return result
}

// GetEnvFunc returns the getEnv function. Fallback to GetOSEnv.
func (hcao HTTPClientAuthenticatorOptions) GetEnvFunc() goenvconf.GetEnvFunc {
	if hcao.GetEnv == nil {
		return goenvconf.GetOSEnv
	}

	return hcao.GetEnv
}

// HTTPClientAuthenticatorOption defines a function to modify [HTTPClientAuthenticatorOptions].
type HTTPClientAuthenticatorOption func(*HTTPClientAuthenticatorOptions)

// WithGetEnvFunc returns a function to set the GetEnvFunc getter to [HTTPClientAuthenticatorOptions].
func WithGetEnvFunc(
	getFunc goenvconf.GetEnvFunc,
) HTTPClientAuthenticatorOption {
	return func(hao *HTTPClientAuthenticatorOptions) {
		if getFunc == nil {
			return
		}

		hao.GetEnv = getFunc
	}
}
